import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@backend/lib/prisma'
import { verifyToken } from '@backend/lib/auth'

export async function PATCH(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const token = request.cookies.get('auth-token')?.value
    if (!token) {
      return NextResponse.json(
        { message: 'Không có quyền truy cập' },
        { status: 401 }
      )
    }

    const user = verifyToken(token)
    if (!user) {
      return NextResponse.json(
        { message: 'Token không hợp lệ' },
        { status: 401 }
      )
    }

    if (user.role !== 'ADMIN') {
      return NextResponse.json(
        { message: 'Chỉ admin mới có quyền duyệt lịch đặt' },
        { status: 403 }
      )
    }

    const { status, rejectionReason } = await request.json()

    if (!['APPROVED', 'REJECTED'].includes(status)) {
      return NextResponse.json(
        { message: 'Trạng thái không hợp lệ' },
        { status: 400 }
      )
    }

    const booking = await prisma.culturalCenterBooking.findUnique({
      where: { id: params.id },
      include: {
        user: {
          select: {
            id: true,
            name: true,
            email: true
          }
        },
        culturalCenter: {
          select: {
            id: true,
            name: true,
            building: true
          }
        }
      }
    })

    if (!booking) {
      return NextResponse.json(
        { message: 'Không tìm thấy lịch đặt' },
        { status: 404 }
      )
    }

    // Check for conflicts if approving
    if (status === 'APPROVED') {
      const conflictingBooking = await prisma.culturalCenterBooking.findFirst({
        where: {
          id: { not: params.id },
          culturalCenterId: booking.culturalCenterId,
          status: 'APPROVED',
          OR: [
            {
              AND: [
                { startTime: { lte: booking.startTime } },
                { endTime: { gt: booking.startTime } }
              ]
            },
            {
              AND: [
                { startTime: { lt: booking.endTime } },
                { endTime: { gte: booking.endTime } }
              ]
            },
            {
              AND: [
                { startTime: { gte: booking.startTime } },
                { endTime: { lte: booking.endTime } }
              ]
            }
          ]
        }
      })

      if (conflictingBooking) {
        return NextResponse.json(
          { message: 'Thời gian này đã được đặt bởi người khác. Không thể duyệt.' },
          { status: 400 }
        )
      }
    }

    // Prepare update data
    const updateData: any = { 
      status,
      lastSyncedAt: new Date()
    }

    if (status === 'APPROVED') {
      updateData.approvedBy = user.id
      updateData.rejectedBy = null
      updateData.rejectionReason = null
      updateData.autoCancelled = false
    } else {
      updateData.rejectedBy = user.id
      updateData.approvedBy = null
      updateData.rejectionReason = rejectionReason || null
    }

    const updatedBooking = await prisma.culturalCenterBooking.update({
      where: { id: params.id },
      data: updateData,
      include: {
        culturalCenter: {
          select: {
            id: true,
            name: true,
            building: true,
            floor: true,
            room: true,
            capacity: true
          }
        },
        user: {
          select: {
            id: true,
            name: true
          }
        }
      }
    })

    // Create activity log
    await prisma.activityLog.create({
      data: {
        action: status,
        entity: 'BOOKING',
        entityId: params.id,
        userId: booking.user.id,
        adminId: user.id,
        details: JSON.stringify({
          title: booking.title,
          culturalCenter: booking.culturalCenter.name,
          startTime: booking.startTime,
          endTime: booking.endTime,
          rejectionReason: rejectionReason || null
        })
      }
    })

    // Create notification for user
    await prisma.notification.create({
      data: {
        title: status === 'APPROVED' ? 'Lịch đặt đã được duyệt' : 'Lịch đặt bị từ chối',
        message: status === 'APPROVED' 
          ? `Lịch đặt "${booking.title}" tại ${booking.culturalCenter.name} đã được duyệt thành công bởi ${user.name}.`
          : `Lịch đặt "${booking.title}" đã bị từ chối${rejectionReason ? `: ${rejectionReason}` : ''}.`,
        userId: booking.user.id,
        type: status === 'APPROVED' ? 'SUCCESS' : 'ERROR',
        autoGenerated: true
      }
    })

    return NextResponse.json(updatedBooking)
  } catch (error) {
    console.error('Error updating booking status:', error)
    return NextResponse.json(
      { message: 'Có lỗi xảy ra khi cập nhật trạng thái lịch đặt' },
      { status: 500 }
    )
  }
}
