import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@backend/lib/prisma'
import { verifyToken } from '@backend/lib/auth'

export async function PATCH(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const token = request.cookies.get('auth-token')?.value
    if (!token) {
      return NextResponse.json(
        { message: 'Không có quyền truy cập' },
        { status: 401 }
      )
    }

    const user = verifyToken(token)
    if (!user) {
      return NextResponse.json(
        { message: 'Token không hợp lệ' },
        { status: 401 }
      )
    }

    if (user.role !== 'ADMIN') {
      return NextResponse.json(
        { message: 'Chỉ admin mới có quyền duyệt yêu cầu' },
        { status: 403 }
      )
    }

    const { status, rejectionReason } = await request.json()

    if (!['APPROVED', 'REJECTED'].includes(status)) {
      return NextResponse.json(
        { message: 'Trạng thái không hợp lệ' },
        { status: 400 }
      )
    }

    const requestData = await prisma.request.findUnique({
      where: { id: params.id },
      include: {
        user: {
          select: {
            id: true,
            name: true,
            email: true
          }
        }
      }
    })

    if (!requestData) {
      return NextResponse.json(
        { message: 'Không tìm thấy yêu cầu' },
        { status: 404 }
      )
    }

    // Prepare update data
    const updateData: any = { 
      status,
      lastSyncedAt: new Date()
    }

    if (status === 'APPROVED') {
      updateData.approvedBy = user.id
      updateData.rejectedBy = null
      updateData.rejectionReason = null
    } else {
      updateData.rejectedBy = user.id
      updateData.approvedBy = null
      updateData.rejectionReason = rejectionReason || null
    }

    const updatedRequest = await prisma.request.update({
      where: { id: params.id },
      data: updateData,
      include: {
        user: {
          select: {
            id: true,
            name: true,
            email: true
          }
        },
        household: {
          select: {
            id: true,
            householdId: true,
            address: true
          }
        }
      }
    })

    // Create activity log
    await prisma.activityLog.create({
      data: {
        action: status,
        entity: 'REQUEST',
        entityId: params.id,
        userId: requestData.user.id,
        adminId: user.id,
        details: JSON.stringify({
          requestType: requestData.type,
          description: requestData.description,
          rejectionReason: rejectionReason || null
        })
      }
    })

    // Create notification for user
    await prisma.notification.create({
      data: {
        title: status === 'APPROVED' ? 'Yêu cầu đã được duyệt' : 'Yêu cầu bị từ chối',
        message: status === 'APPROVED' 
          ? `Yêu cầu "${requestData.description}" đã được duyệt thành công bởi ${user.name}.`
          : `Yêu cầu "${requestData.description}" đã bị từ chối${rejectionReason ? `: ${rejectionReason}` : ''}.`,
        userId: requestData.user.id,
        type: status === 'APPROVED' ? 'SUCCESS' : 'ERROR',
        autoGenerated: true
      }
    })

    return NextResponse.json(updatedRequest)
  } catch (error) {
    console.error('Error updating request status:', error)
    return NextResponse.json(
      { message: 'Có lỗi xảy ra khi cập nhật trạng thái yêu cầu' },
      { status: 500 }
    )
  }
}
